tabWidth: 2
semi: false
singleQuote: true
trailingComma: 'es5'
singleAttributePerLine: true
plugins:
  - 'prettier-plugin-tailwindcss'
  - 'prettier-plugin-css-order'
  - 'prettier-plugin-organize-imports' # Must be last
overrides:
  - files: '*.ts'
    options:
      parser: 'typescript'
  - files: '*.tsx'
    options:
      parser: 'typescript'
  - files: '*.js'
    options:
      parser: 'babel'
  - files: '*.jsx'
    options:
      parser: 'babel'
  - files: '*.css'
    options:
      parser: 'css'
  - files: '*.scss'
    options:
      parser: 'css'
  - files: '*.mdx'
    options:
      parser: 'mdx'
      singleAttributePerLine: false
  - files: '*.yml'
    options:
      parser: 'yaml'
